### ISSUE TITLE
Use correct server port number for rsync

### ISSUE THREAD

**Issue by ezekg** [Bladrak/capistrano-rsync#21]
See [this question on StackOverflow for a possible solution](http://stackoverflow.com/questions/4549945/is-it-possible-to-specify-a-different-ssh-port-when-using-rsync). Even if you have an alternate port set via Capistrano, it does not get set when `rsync` is executed, resulting in a failed deployment. Let me know if you need some help and I'll be happy to issue a pull request.

Example server,

``` ruby
server "192.168.1.1:2222", {
  # ...
}
```

Possible solution derived one of the StackOverflow answers:

``` ruby
"rsync -e 'ssh -p #{port}' user@remoteip:/path/to/files/ /local/path/"
```

**Comment by ezekg** [comment]
I have a fork (https://github.com/ezekg/capistrano-rsync/commit/a8f74e55a65342f8d348f0e7a0b583df67ca8b8a) that I'll try to test on Monday. I'm not sure what kind of implications that change might cause, but I'm thinking it should work (it works by manually adding that line to `:rsync_options`, but I have different servers with differing ports).

**Comment by Bladrak** [comment]
Thanks for reporting that. I think we could add an option `:rsync_ssh_command` to handle this use case. What do you think about it?

**Comment by ezekg** [comment]
That's a great idea. Would allow a lot more flexibility other than just what I'm proposing as well. You would have to make sure that the port number is dynamically inserted, though.

**Comment by Bladrak** [comment]
That could be done as well yes, but in that case, I'm afraid the options would become more complicated to use (and they're quite complicated to use already :/).

**Comment by ezekg** [comment]
Then I would suggest adding this in (`-e 'ssh -p #{port}'`) automatically if a port number is specified for a server, otherwise the deploy fails because Rsync can't connect. See https://github.com/ezekg/capistrano-rsync/commit/a8f74e55a65342f8d348f0e7a0b583df67ca8b8a. I can make a pull request if you'd like, so that we could review the change.

**Comment by Bladrak** [comment]
Fine with me, could you submit a Pull Request with this?

**Comment by ezekg** [comment]
Done and done: https://github.com/Bladrak/capistrano-rsync/pull/22.

**Comment by Bladrak** [comment]
Thanks, closing this issue then :)

**Comment by Bladrak** [comment]
I issued 1.3.8 version on rubygems

**Comment by ezekg** [comment]
Works like a charm here. Thanks. :+1:
